import type { PublicItem } from "./types";

/**
 * What the shop shows before Supabase is set up, so every deploy renders a complete site.
 * The photos are drawings in public/sample/. Shown until SHOP_API_URL points at the Mac mini.
 */
const base = {
  compareAtCents: null,
  status: "live" as const,
  quantity: 1,
  heldUntil: null,
  obo: false,
  pickup: true,
  ships: false,
  shippingCents: null,
  featured: false,
  channels: {},
  size: "",
  brand: "",
  soldAt: null,
  soldVia: null,
};

const at = (daysAgo: number) => new Date(Date.UTC(2026, 8, 30) - daysAgo * 86_400_000).toISOString();
const photo = (name: string) => [{ url: `/sample/${name}.svg`, width: 1200, height: 1200 }];

export const SAMPLE_ITEMS: PublicItem[] = [
  {
    ...base,
    id: "sample-1",
    slug: "mid-century-armchair",
    title: "Mid-century armchair",
    description: "Walnut frame, mustard upholstery. Comfortable and sturdy, a few light scratches on one arm.\n\nAbout 30\" wide × 32\" tall.",
    priceCents: 8500,
    compareAtCents: 12000,
    condition: "good",
    category: "furniture",
    photos: photo("chair"),
    featured: true,
    obo: true,
    publishedAt: at(1),
    createdAt: at(1),
    updatedAt: at(1),
  },
  {
    ...base,
    id: "sample-2",
    slug: "road-bike-54cm",
    title: "Road bike, 54 cm",
    description: "Aluminum frame, 18 speeds, new tires this spring. Rides great.",
    priceCents: 22000,
    condition: "good",
    category: "auto",
    photos: photo("bike"),
    featured: true,
    publishedAt: at(2),
    createdAt: at(2),
    updatedAt: at(2),
  },
  {
    ...base,
    id: "sample-3",
    slug: "stand-mixer",
    title: "Stand mixer with three attachments",
    description: "Works perfectly. Comes with the whisk, paddle and dough hook.",
    priceCents: 9000,
    condition: "like_new",
    category: "home",
    photos: photo("mixer"),
    ships: true,
    shippingCents: 2500,
    publishedAt: at(3),
    createdAt: at(3),
    updatedAt: at(3),
  },
  {
    ...base,
    id: "sample-4",
    slug: "box-of-paperbacks",
    title: "Box of paperbacks (about 40)",
    description: "Mostly mysteries and sci-fi. Take the whole box.",
    priceCents: 2000,
    condition: "good",
    category: "media",
    photos: photo("books"),
    publishedAt: at(4),
    createdAt: at(4),
    updatedAt: at(4),
  },
  {
    ...base,
    id: "sample-5",
    slug: "cordless-drill-set",
    title: "Cordless drill set",
    description: "Drill/driver, two batteries, charger and case.",
    priceCents: 4500,
    condition: "good",
    category: "tools",
    photos: photo("drill"),
    ships: true,
    shippingCents: 1500,
    publishedAt: at(5),
    createdAt: at(5),
    updatedAt: at(5),
  },
  {
    ...base,
    id: "sample-6",
    slug: "table-lamp",
    title: "Ceramic table lamp",
    description: "Teal glaze, linen shade.",
    priceCents: 2500,
    condition: "like_new",
    category: "home",
    photos: photo("lamp"),
    status: "sold",
    quantity: 0,
    soldAt: at(1),
    publishedAt: at(6),
    createdAt: at(6),
    updatedAt: at(1),
  },
];
